# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  山河蒙水
description: "兔子一生只做一件事"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sarahqinsarah.github.io" # the base hostname & protocol for your site, e.g.http://example.com
repository: "sarahqinsarah/sarahqinsarah.github.io"
logo: "/images/hatted_bunny.png"
date_format: "%Y-%m-%d"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
disqus:
  shortname: dudu # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: SarahQin11# site's Twitter username, e.g. "mmistakes"

# Build settings
permalink: /:categories/:title/
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/light.css"
feed:
  path: atom.xml
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Liquid
liquid:
  error_mode: strict

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: false
      sitemap: true

# Site Author
name: 小秦秦
picture: /images/strong_bunny.jpg
links:
  - title: Instagram
    url: https://instagram.com/sarah_qinnn
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/sarahqinsarah
    icon: fab fa-github-square
  - title: Weibo
    url: https://weibo.com/u/7393304133
    icon: fab fa-weibo


# robots.txt setting
production: true # If false, robots.txt will disallow every crawling.
